FROM node:latest

# upage
RUN apt-get update -y

 RUN apt-get install -y \
  wget \
  xvfb \
  x11-xkb-utils \
  xfonts-100dpi \
  xfonts-75dpi \
  xfonts-scalable \
  xfonts-cyrillic \
  x11-apps \
  clang \
  libxss1 \
  gcc-multilib \
  g++-multilib


# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# If running Docker >= 1.13.0 use docker run's --init arg to reap zombie processes, otherwise
# uncomment the following lines to have `dumb-init` as PID 1
# ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
# RUN chmod +x /usr/local/bin/dumb-init
# ENTRYPOINT ["dumb-init", "--"]

# Uncomment to skip the chromium download when installing puppeteer. If you do,
# you'll need to launch puppeteer with:
#     browser.launch({executablePath: 'google-chrome-unstable'})

ENV PLAYWRIGHT_EXEC_PATH google-chrome-unstable

# COPY Files
COPY package.json package.json
COPY playwright/ .
RUN npm i

# COPY Extension
COPY ./chrome /browser-extension/dist/chrome

# Install puppeteer so it's available in the container.
RUN npm i playwright \
    # Add user so we don't need --no-sandbox.
    # same layer as npm install to keep re-chowned files from using up several hundred MBs more space
    && groupadd -r pluser && useradd -r -g pluser -G audio,video pluser \
    && mkdir -p /home/pluser/Downloads \
    && chown -R pluser:pluser /home/pluser \
    && chown -R pluser:pluser /node_modules

RUN npm run compile


# Run everything after as non-privileged user.
USER pluser

CMD xvfb-run -a --server-args='-screen 0 1024x768x24' npm run testPlaywright