FROM mcr.microsoft.com/playwright:v1.8.1-focal

# upage
RUN apt-get update -y

RUN apt-get upgrade -y && apt-get install -y --no-install-recommends \
  git \
  g++ \
  fontconfig \
  fonts-ipafont-gothic \
  fonts-wqy-zenhei \
  fonts-thai-tlwg \
  fonts-kacst \
  fonts-freefont-ttf \
  make \
  python \
  zstd \
  libpcap-dev 


RUN apt-get install -y \
  wget \
  xvfb \
  x11-xkb-utils \
  xfonts-100dpi \
  xfonts-75dpi \
  xfonts-scalable \
  xfonts-cyrillic \
  x11-apps \
  clang \
  libxss1 \
  gcc-multilib \
  g++-multilib


# Add user so we don't need --no-sandbox.
# same layer as npm install to keep re-chowned files from using up several hundred MBs more space
RUN groupadd -r pluser && useradd -r -g pluser -G audio,video pluser \
  && mkdir -p /home/pluser \
  && chown -R pluser:pluser /home/pluser 



# Run everything after as non-privileged user.
USER pluser
WORKDIR /home/pluser


# COPY Files
COPY --chown=pluser package.json package.json
COPY --chown=pluser tsconfig-playwright.json tsconfig.json
COPY --chown=pluser playwright/ playwright/

# COPY Extension
COPY --chown=pluser ./chrome /browser-extension/dist/chrome

# Make npm global for pluser
RUN mkdir ~/.npm-global && npm config set prefix '~/.npm-global' 
RUN echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.profile


# Install playwright so it's available in the container.
RUN npm i playwright

# Install projects dependencies
RUN npm install

# Compile project files
RUN npm run compile

CMD xvfb-run -a --server-args='-screen 0 1024x768x24' npm run testPlaywright