version: "3.3"
services:
  reverseproxy:
    build:
      context: reverseproxy/
      dockerfile: ./Dockerfile.prod
    volumes:
      - type: bind
        source: ${CERTIFICAT_SOURCE}
        target: ${CERTIFICAT_TARGET}
        read_only: true
    ports:
      - 80:80
      - 443:443

  initialization:
    build:
      context: initialization/
      dockerfile: ./Dockerfile
    depends_on:
      - "website"
      - "account"
    