version: "3.3"
services:

  website:
    build:
      context: website/
      dockerfile: ./Dockerfile.prod
    environment:
      -  NODE_ENV=github
    depends_on:
      - "mongo"
    ports:
      - 5000:80
    
  session:
    build:
      context: session/
      dockerfile: ./Dockerfile.prod
    environment:
      -  NODE_ENV=github
    depends_on:
      - "mongo"
      - "website"
    ports:
      - 5001:80
    volumes:
      - screenshot:/app/screenshot
      - video:/app/public/video
    restart: always

  model:
    build:
      context: model/
      dockerfile: ./Dockerfile.prod
    environment:
      -  NODE_ENV=github
    depends_on:
      - "mongo"
      - "session"
    ports:
      - 5002:80
    restart: always

  evaluator:
    build:
      context: evaluator/
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./model/src/:/app/src
    ports:
      - 5003:80
  
  account:
    build:
      context: account/
      dockerfile: ./Dockerfile.prod
    environment:
      -  NODE_ENV=github
    depends_on:
      - "mongo"
    ports:
      - 5004:80
    restart: always

  dashboard:
    build:
      context: dashboard/
      dockerfile: ./Dockerfile.prod
    environment:
      -  NODE_ENV=github
    volumes:
      - screenshot:/app/public/screenshot
      - video:/app/public/video

  api:
    build:
      context: api/
      dockerfile: ./Dockerfile.prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
    depends_on:
      - "account"
      - "website"
      - "session"
      - "model"
    restart: always


  reverseproxy:
    build:
      context: reverseproxy/
      dockerfile: ./Dockerfile.dev
    depends_on:
      - "model"
      - "website"
      - "session"
      - "dashboard"
    ports:
      - 80:80
  

  initialization:
    build:
      context: initialization/
      dockerfile: ./Dockerfile
    command: npm start
    depends_on:
      - "website"
      - "account"
    
  test:
    build:
      context: test/
      dockerfile: ./Dockerfile.github
    environment:
      -  NODE_ENV=github
    depends_on:
      - "mongo"
      - "session"
      - "website"
      - "dashboard"  


  rabbitmq:
    image: rabbitmq:3.8.5
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db

volumes:
    screenshot:
    video:
    db-data:
