FROM node:14.16.0-slim as builder

# install python (needed by npm-gyp)
RUN apt-get update

# Create app directory
WORKDIR /app

COPY ./package.json /app/package.json
RUN npm install

# Install app dependencies
RUN npm install -g typescript

COPY ./tsconfig.json /app

COPY ./src /app/src

RUN tsc

FROM node:14.16.0-slim

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt=

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY ./package.json /app/package.json
COPY ./nodemon.json /app/nodemon.json
COPY ./tsconfig.json /app/tsconfig.json


# Run app.py when the container launches
CMD npm run dev

# Make port available to the world outside this container
EXPOSE 5010