FROM node:16

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app/

# Install any needed packages specified in requirements.txt
RUN npm install

# Run when the container launches
CMD npm start

# Make port available to the world outside this container
EXPOSE 80