openapi: '3.0.2'
info:
  title: AIFEX Evaluator OpenAPI
  version: '0.10.11'
servers:
  - url: http://localhost/evaluator
    variables:
      port: 
        default: "5003"
        
paths:
  /ping:
    summary: Checks if the server is alive
    description: Checks if the server is alive
    get:
      responses:
        '200':
          description: Returns Alive
          
  /evaluator/{sessionId}:
    summary: Returns an evaluator
    description: This resource represent the evaluation configuration for the evaluator associated to a session
    get:
      parameters:
        - name: sessionId
          in: path
          description: session associated to the requested evaluator
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The current configuration of the evaluator
          content:
            application/json:
              schema:
                properties:
                  id: 
                    type: string
                  description:
                    type: string
                  expression:
                    type: string
                  sessionId:
                    type: string

  /evaluator/create:
    summary: Create a new evaluator for the session
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId: 
                  description: session associated to the requested evaluator
                  type: string
                description: 
                  description: The description for the behaviour evaluated
                  type: string
                expression: 
                  description: The pattern of actions evaluated, must be encoded with our DSL
                  type: string
      responses:
        '200':
          description: Evaluator created successfully        
  
  /evaluator/update/{sessionId}:
    summary: Update the evaluator of the session
    post:
      parameters:
        - name: sessionId
          in: path
          description: session associated to the requested evaluator
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:        
                description: 
                  description: The description for the behaviour evaluated
                  type: string
                expression:
                  description: The pattern of actions evaluated, must be encoded with our DSL
                  type: string
      responses:
          '200':
            description: Evaluator updated successfully       
  
  /evaluator/remove/{sessionId}:
    summary: Remove the evaluator associated with the session
    description: Remove the evaluator associated with the session
    post:
      parameters:
        - name: sessionId
          in: path
          description: session associated to the requested evaluator
          required: true
          schema:
            type: string
      responses:
          '200':
            description: Evaluator removed successfully       

  /evaluator/evaluate:
    summary: Evaluate a list of action using the session Evaluator
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                sessionId:
                  type: string
                actionList:
                  $ref: '#components/schemas/actionList'
      responses:
          '200':
            description: Evaluator created updated      

components:
  schemas:
    actionList:
      type: array
      items:
        type: object
        properties:   
          prefix:
            type: string
          suffix: 
            type: string
    evaluation:
      properties:
        isAccepted: 
          type: boolean
        nextActionList:
          type: array
          items:
            type: object
            properties:
              prefix: 
                type: string
              suffix: 
                type: string

