openapi: '3.0.2'
info:
  title: AIFEX OpenAPI
  version: '0.10.11'
servers:
  - url: http://localhost/api
paths:
  /ping:
    get:
      responses:
        '200':
          description: Returns Alive
  /signin:
    description: returns the JWT token
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Returns JWT Token
  /websites:
    get:
      description: returns WebSite ids
      responses:
        '200':
          description: The WebSite ids
      security:
        - bearerAuth: []
    post:
      description: add a new WebSite
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                mappingList:
                  type: array
                  items:
                    type: object
                    properties:
                      match:
                        type: object
                        properties:
                          event:
                            type: string
                          css:
                            type: string
                          xpath:
                            type: string
                          code:
                            type: string
                          key:
                            type: string
                      output:
                        type: object
                        properties:
                          prefix:
                            type: string
                          suffix:
                            type: string
                      context:
                        type: object
                        properties:
                          url:
                            type: string
                          css:
                            type: string
                          xpath:
                            type: string
                      description:
                        type: string
      responses:
        '200':
          description: The WebSite ids
      security:
        - bearerAuth: []
  /websites/{webSiteId}:
    get:
      description: returns WebSite 
      parameters:
        - in: path
          name: webSiteId
          schema:
            type: string
          required: true
          description: ID of the WebSite to get
      responses:
        '200':
          description: Returns WebSite
      security:
        - bearerAuth: []
  /sessions:
    get:
      description: returns Session ids
      responses:
        '200':
          description: Returns Session ids
      security:
        - bearerAuth: []
    post:
      description: add a new session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                webSiteId:
                  type: string
                baseURL:
                  type: string
                name:
                  type: string
                overlayType:
                  type: string
                  enum: [shadow, bluesky, rainbow]
      responses:
        '200':
          description: The WebSite ids
      security:
        - bearerAuth: []        
  /sessions/{sessionId}:
    get:
      description: returns Session 
      parameters:
        - in: path
          name: sessionId
          schema:
            type: string
          required: true
          description: ID of the Session to get
      responses:
        '200':
          description: Returns Session
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT   