on:
  schedule:
    - cron: '0 8 * * 1-5' 
  push:

jobs:
  
  model-npm-package-version-check:
    name: NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: model-npm-check
      working-directory: ./model
      run: |
        npm outdated

  session-npm-package-version-check:
    name: NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: model-npm-check
      working-directory: ./session
      run: |
        npm outdated

  website-npm-package-version-check:
    name: NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: model-npm-check
      working-directory: ./website
      run: |
        npm outdated

  evaluator-npm-package-version-check:
    name: NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: model-npm-check
      working-directory: ./website
      run: |
        npm outdated
