on:
  schedule:
    - cron: '0 8 * * 1-5' 
  push:

jobs:
  
  model-npm-package-version-check:
    name: Model NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: model-npm-install
      working-directory: ./model
      run: |
        npm install 
    - name: model-npm-outdated
      working-directory: ./model
      run: |
        npm outdated

  session-npm-package-version-check:
    name: Session NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: model-npm-install
      working-directory: ./session
      run: |
        npm install 
    - name: session-npm-outdated
      working-directory: ./session
      run: |
        npm outdated

  website-npm-package-version-check:
    name: Website NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: website-npm-install
      working-directory: ./website
      run: |
        npm install 
    - name: website-npm-outdated
      working-directory: ./website
      run: |
        npm outdated

  evaluator-npm-package-version-check:
    name: Evaluator NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: evaluator-npm-install
      working-directory: ./evaluator
      run: |
        npm install 
    - name: evaluator-npm-outdated
      working-directory: ./evaluator
      run: |
        npm outdated

  dashboard-npm-package-version-check:
    name: Dashboard NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: dashboard-npm-install
      working-directory: ./dashboard
      run: |
        npm install 
    - name: dashboard-npm-outdated
      working-directory: ./dashboard
      run: |
        npm outdated

  printer-npm-package-version-check:
    name: Printer NPM version check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: printer-npm-install
      working-directory: ./printer
      run: |
        npm install 
    - name: printer-npm-outdated
      working-directory: ./printer
      run: |
        npm outdated